### ISSUE TITLE
Exception when attempting to import via CLI

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#37]
I'm seeing the following exception when I attempt to import via the `-import` subcommand. The user I specify with the `-user` option does have write privileges and is able to import without issue through the GUI.

This was observed on 1.4.27

```
CCDD : CCDD Error : An unanticipated error occurred; cause 'null'  Error trace:   CcddFileIOHandler: createTablesFromDefinitions() line 1291   CcddFileIOHandler: importFile() line 868   CcddCommandLineHandler: doCommand() line 1025   CcddCommandLineHandlerCommandHandler: handler() line 363   CcddCommandLineHandler: parseCommand() line 1739   CcddCommandLineHandler: parseCommand() line 1605   CcddMain: parseDbSpecificCommandLineCommands() line 847   CcddDbControlHandler: complete() line 2631   CcddBackgroundCommand: done() line 192
Error: Import disabled; user lacks write access
```

**Comment by KevinMcCluney** [comment]
The error will be corrected in the next release.

**Comment by ascended121** [comment]
In 1.4.30 I'm still observing the following error when importing via the CLI:
```
CCDD : CCDD Error : An unanticipated error occurred; cause 'null'  Error trace:   CcddFileIOHandler: createTablesFromDefinitions() line 1064   CcddFileIOHandler: importFile() line 871   CcddCommandLineHandler: doCommand() line 1051   CcddCommandLineHandlerCommandHandler: handler() line 379   CcddCommandLineHandler: parseCommand() line 2002   CcddCommandLineHandler: parseCommand() line 1868   CcddMain: parseDbSpecificCommandLineCommands() line 848   CcddDbControlHandler: complete() line 2656   CcddBackgroundCommand: done() line 192
```

**Comment by ascended121** [comment]
This same exception still appears when importing via CLI in 1.4.31.

**Comment by KevinMcCluney** [comment]
Version 1.4.32 has been uploaded with the correction.
