### ISSUE TITLE
Import XTCE data error

### ISSUE THREAD

**Issue by hakuho** [nasa/CCDD#77]
When importing an XTCE file that was generated using the XTCE_export.js script, I receive the following CCDD Error:

> An unanticipated error occurred; cause 'For input string: "System Path"'
> 
> Error trace:
> CcddFieldHandler: getFieldInformationFromData() line 599
> CcddFileIOHandler: importSelectedFileIntoTable() line 2540
> CcddTableEditorDialog: performAction() line 742
> CcddClassesComponentValidateCellActionListener: actionPerformed() line 181

CCDD Version 2.0.16
Ubuntu 18.04.2 LTS
Java 8
PostgreSQL 10.12

The XTCE file used:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<SpaceSystem xmlns="http://www.omg.org/space/xtce" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="myproject" shortDescription="myproject" xsi:schemaLocation="http://www.omg.org/spec/XTCE/20061101 06-11-06.xsd">
   <LongDescription>Project containing interface definitions</LongDescription>
   <AncillaryDataSet>
      <AncillaryData name="XML: Application ID">applicationID</AncillaryData>
      <AncillaryData name="XML: Function Code">functionCode</AncillaryData>
   </AncillaryDataSet>
   <Header classification="DOMAIN" date="Fri May 01 09:36:13 PDT 2020" validationStatus="Working" version="1.0">
      <AuthorSet>
         <Author>hakuho</Author>
      </AuthorSet>
      <NoteSet>
         <Note>CCDD Version: 2.0.16 (5-1-2020)</Note>
         <Note>Date: Fri May 01 09:36:13 PDT 2020</Note>
         <Note>Project: myproject</Note>
         <Note>Host: localhost:5432</Note>
         <Note>Endianess: big</Note>
      </NoteSet>
   </Header>
   <SpaceSystem name="MyStructure" shortDescription="MyStructure">
      <Header classification="INTERFACE" validationStatus="Working" version="1.0"/>
      <TelemetryMetaData>
         <ParameterTypeSet>
            <EnumeratedParameterType name="engine_arm_Type">
               <LongDescription>Engine armed Status</LongDescription>
               <UnitSet/>
               <IntegerDataEncoding bitOrder="mostSignificantBitFirst" encoding="unsigned" sizeInBits="1"/>
               <EnumerationList>
                  <Enumeration label="Off" value="0"/>
                  <Enumeration label="Arm" value="1"/>
               </EnumerationList>
            </EnumeratedParameterType>
            <EnumeratedParameterType name="engine_fire_Type">
               <LongDescription>Engine fire status</LongDescription>
               <UnitSet/>
               <IntegerDataEncoding bitOrder="mostSignificantBitFirst" encoding="unsigned" sizeInBits="1"/>
               <EnumerationList>
                  <Enumeration label="Off" value="0"/>
                  <Enumeration label="Fire" value="1"/>
               </EnumerationList>
            </EnumeratedParameterType>
         </ParameterTypeSet>
         <ParameterSet>
            <Parameter name="engine_arm" parameterTypeRef="engine_arm_Type"/>
            <Parameter name="engine_fire" parameterTypeRef="engine_fire_Type"/>
         </ParameterSet>
         <ContainerSet>
            <SequenceContainer name="MyStructure">
               <EntryList>
                  <ParameterRefEntry parameterRef="engine_arm"/>
                  <ParameterRefEntry parameterRef="engine_fire"/>
               </EntryList>
            </SequenceContainer>
         </ContainerSet>
      </TelemetryMetaData>
   </SpaceSystem>
</SpaceSystem>
```

**Comment by bawi235** [comment]
CCDD 2.0.16 was having issues with XTCE and EDS import/exports. I just released CCDD 2.0.20 and while using it I was able to perform the import mentioned above. Give that version a try and see if everything works as expected. I will leave this issue open for another week to see if you still encounter problems.

**Comment by hakuho** [comment]
Thanks for the assistance.

I now can import XTCE files from the command line and from the CCDD main window menu bar **Data | Import Data**  but I still get the same error when I try importing from the **Table Editor**.

> An unanticipated error occurred; cause 'For input string: "System Path"
Error trace:
CcddFieldHandler: getFieldInformationFromData() line 523
CcddFileIOHandler: importSelectedFileIntoTable() line 2158
CcddTableEditorDialog: performAction() line 691
CcddClassesComponentValidateCellActionListener: actionPerformed() line 175

**Comment by bawi235** [comment]
Thanks for the feedback. I will look into the table editor imports and see what is going on.

**Comment by bawi235** [comment]
Version 2.0.21 is out. It contains fixes for the table editor imports. Try it out and let me know if you are still having problems. If not I will close this issue in a week or so.
